### ISSUE TITLE
There is not level shifter between ToF and Atmega

### ISSUE THREAD

**Issue by leroilion** [sylvaing19/ToF-Module#1]
You have level shifter between Tof and Atmega for I2C (to transform Vin value to 2.8V).

But you don't have level shifter for signal *XSHUT* and *IRQ*

May be, you can set the voltage of ATmega328P to 2.8V and have level shifter for external connector ==> The internal of the board is all in 2.8V.

**Comment by sylvaing19** [comment]
The level shifter il not mandatory here
2.8V is high enough to be considered as logic-high by the Atmega so we can read from the sensor
And to write we simply switch between "input mode" and "output mode LOW" on the Atmega pin
